//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsTweeting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoIsTweeting.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any issues, email me:.
        /// </summary>
        public static string About_Email {
            get {
                return ResourceManager.GetString("About_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by PicoBird Twitter Library!.
        /// </summary>
        public static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoIsTweeting, PicoBird and Newtonsoft.Json are
        ///licensed under the MIT License. See enclosed LICENSE file
        ///for full text of the license..
        /// </summary>
        public static string About_PoweredBy_License {
            get {
                return ResourceManager.GetString("About_PoweredBy_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks.
        /// </summary>
        public static string About_Thanks {
            get {
                return ResourceManager.GetString("About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to give special thanks to
        ///Macchiato (@CreStudio_Plus), for this awesome idea..
        /// </summary>
        public static string About_ThanksText {
            get {
                return ResourceManager.GetString("About_ThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WhoIsTweeting.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Website:.
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Now.
        /// </summary>
        public static string Button_TryAgain {
            get {
                return ResourceManager.GetString("Button_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the consumer key and the consumer secret cannot be left blank..
        /// </summary>
        public static string Consumer_Empty_Error {
            get {
                return ResourceManager.GetString("Consumer_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        public static string Consumer_Header_Consumer {
            get {
                return ResourceManager.GetString("Consumer_Header_Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Secret.
        /// </summary>
        public static string Consumer_Header_Secret {
            get {
                return ResourceManager.GetString("Consumer_Header_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy and paste the consumer key and the consumer secret of
        ///your Twitter application. If you do not have an app, you can create one at
        ///https://dev.twitter.com..
        /// </summary>
        public static string Consumer_Message {
            get {
                return ResourceManager.GetString("Consumer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Consumer Key.
        /// </summary>
        public static string Consumer_Title {
            get {
                return ResourceManager.GetString("Consumer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter API Error.
        /// </summary>
        public static string Critical_ApiError {
            get {
                return ResourceManager.GetString("Critical_ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Failed:.
        /// </summary>
        public static string Critical_AuthFailed {
            get {
                return ResourceManager.GetString("Critical_AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recover from errors after {0} retries. Please retry manually..
        /// </summary>
        public static string Critical_AutoRetry_Failed {
            get {
                return ResourceManager.GetString("Critical_AutoRetry_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoIsTweeting will retry updating in {0} seconds..
        /// </summary>
        public static string Critical_AutoRetry_Message {
            get {
                return ResourceManager.GetString("Critical_AutoRetry_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your Internet connection or try signing in again..
        /// </summary>
        public static string Critical_Message {
            get {
                return ResourceManager.GetString("Critical_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string Critical_NetError {
            get {
                return ResourceManager.GetString("Critical_NetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in a few moments....
        /// </summary>
        public static string Critical_Retry {
            get {
                return ResourceManager.GetString("Critical_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string Critical_UnknownError {
            get {
                return ResourceManager.GetString("Critical_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed:.
        /// </summary>
        public static string Critical_UpdateFailed {
            get {
                return ResourceManager.GetString("Critical_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (can handle up to {0} followings).
        /// </summary>
        public static string Interval_MaxFollowingsFormat {
            get {
                return ResourceManager.GetString("Interval_MaxFollowingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can customize the update interval here.
        ///Please note that Twitter API calls are rate limited and
        ///too short interval may cause the app to malfunction,
        ///depending on the number of users you are following..
        /// </summary>
        public static string Interval_Message {
            get {
                return ResourceManager.GetString("Interval_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string Interval_SecondFormat {
            get {
                return ResourceManager.GetString("Interval_SecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Update Interval.
        /// </summary>
        public static string Interval_Title {
            get {
                return ResourceManager.GetString("Interval_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a _Mention....
        /// </summary>
        public static string Menu_Context_Mention {
            get {
                return ResourceManager.GetString("Menu_Context_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Twitter _Profile....
        /// </summary>
        public static string Menu_Context_Profile {
            get {
                return ResourceManager.GetString("Menu_Context_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string Menu_Main_About {
            get {
                return ResourceManager.GetString("Menu_Main_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set _Consumer Key....
        /// </summary>
        public static string Menu_Main_Consumer {
            get {
                return ResourceManager.GetString("Menu_Main_Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set _Update Interval....
        /// </summary>
        public static string Menu_Main_Interval {
            get {
                return ResourceManager.GetString("Menu_Main_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key Required.
        /// </summary>
        public static string Menu_Main_NeedConsumer {
            get {
                return ResourceManager.GetString("Menu_Main_NeedConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign in.
        /// </summary>
        public static string Menu_Main_NeedSignIn {
            get {
                return ResourceManager.GetString("Menu_Main_NeedSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string Menu_Main_Quit {
            get {
                return ResourceManager.GetString("Menu_Main_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign _in/Switch User....
        /// </summary>
        public static string Menu_Main_SignIn {
            get {
                return ResourceManager.GetString("Menu_Main_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Statistics....
        /// </summary>
        public static string Menu_Main_Statistics {
            get {
                return ResourceManager.GetString("Menu_Main_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_way Users.
        /// </summary>
        public static string Menu_View_ShowAway {
            get {
                return ResourceManager.GetString("Menu_View_ShowAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Offline Users.
        /// </summary>
        public static string Menu_View_ShowOffline {
            get {
                return ResourceManager.GetString("Menu_View_ShowOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on _Top.
        /// </summary>
        public static string Menu_View_Topmost {
            get {
                return ResourceManager.GetString("Menu_View_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send a mention..
        /// </summary>
        public static string Message_Error_Mention {
            get {
                return ResourceManager.GetString("Message_Error_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a Mention to.
        /// </summary>
        public static string Message_Header_Mention {
            get {
                return ResourceManager.GetString("Message_Header_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click OK, a web browser will be opened and it will show you the PIN required for authentication..
        /// </summary>
        public static string SignIn_Confirm {
            get {
                return ResourceManager.GetString("SignIn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN was provided. Please try again..
        /// </summary>
        public static string SignIn_Error {
            get {
                return ResourceManager.GetString("SignIn_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input PIN in the text box below
        ///to complete the sign-in process..
        /// </summary>
        public static string SignIn_Message {
            get {
                return ResourceManager.GetString("SignIn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Twitter.
        /// </summary>
        public static string SignIn_Title {
            get {
                return ResourceManager.GetString("SignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. online.
        /// </summary>
        public static string Stat_AvgOnline {
            get {
                return ResourceManager.GetString("Stat_AvgOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Stat_Away {
            get {
                return ResourceManager.GetString("Stat_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string Stat_Button_Export {
            get {
                return ResourceManager.GetString("Stat_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string Stat_Button_Reset {
            get {
                return ResourceManager.GetString("Stat_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from.
        /// </summary>
        public static string Stat_DataFrom {
            get {
                return ResourceManager.GetString("Stat_DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to.
        /// </summary>
        public static string Stat_DataTo {
            get {
                return ResourceManager.GetString("Stat_DataTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Stat_Date {
            get {
                return ResourceManager.GetString("Stat_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export: {0}.
        /// </summary>
        public static string Stat_Export_Exception {
            get {
                return ResourceManager.GetString("Stat_Export_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated Values|*.csv.
        /// </summary>
        public static string Stat_Export_Filter {
            get {
                return ResourceManager.GetString("Stat_Export_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export: Invalid file format.
        /// </summary>
        public static string Stat_Export_InvalidType {
            get {
                return ResourceManager.GetString("Stat_Export_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Statistics Data.
        /// </summary>
        public static string Stat_Export_Title {
            get {
                return ResourceManager.GetString("Stat_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. online.
        /// </summary>
        public static string Stat_MaxOnline {
            get {
                return ResourceManager.GetString("Stat_MaxOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. online.
        /// </summary>
        public static string Stat_MinOnline {
            get {
                return ResourceManager.GetString("Stat_MinOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of data.
        /// </summary>
        public static string Stat_NumOfData {
            get {
                return ResourceManager.GetString("Stat_NumOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data: {0}.
        /// </summary>
        public static string Stat_NumOfDataFormat {
            get {
                return ResourceManager.GetString("Stat_NumOfDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Stat_Offline {
            get {
                return ResourceManager.GetString("Stat_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Stat_Online {
            get {
                return ResourceManager.GetString("Stat_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really reset the statistics data?.
        /// </summary>
        public static string Stat_Reset_Message {
            get {
                return ResourceManager.GetString("Stat_Reset_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Statistics Data.
        /// </summary>
        public static string Stat_Reset_Title {
            get {
                return ResourceManager.GetString("Stat_Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Stat_Tab_Graph {
            get {
                return ResourceManager.GetString("Stat_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Stat_Tab_Table {
            get {
                return ResourceManager.GetString("Stat_Tab_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Stat_Title {
            get {
                return ResourceManager.GetString("Stat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Away.
        /// </summary>
        public static string Status_Away {
            get {
                return ResourceManager.GetString("Status_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Offline.
        /// </summary>
        public static string Status_Offline {
            get {
                return ResourceManager.GetString("Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Online.
        /// </summary>
        public static string Status_Online {
            get {
                return ResourceManager.GetString("Status_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
    }
}
